services:
  - type: web
    name: finzanzapp-9xgw
    env: python
    plan: starter
    repo: https://github.com/lucasmurray97/finzanzapp
    branch: main
    rootDir: finanzapp_proj
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn finanzapp_proj.wsgi:application
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: ALLOWED_HOSTS
        value: "finzanzapp-9xgw.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://finzanzapp-9xgw.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: finanzapp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false

databases:
  - name: finanzapp-db
    plan: starter
